// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 32A6R5tEk8Q2nVvJmPnVbf
// Component: VTcoPS-NzQ
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { LottieWrapper } from "@plasmicpkgs/lottie-react"; // plasmic-import: BPNsJ2qis6/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_generic_landing_page.module.css"; // plasmic-import: 32A6R5tEk8Q2nVvJmPnVbf/projectcss
import sty from "./PlasmicShieldLabel.module.css"; // plasmic-import: VTcoPS-NzQ/css

export const PlasmicShieldLabel__VariantProps = new Array();

export const PlasmicShieldLabel__ArgProps = new Array();

function PlasmicShieldLabel__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <LottieWrapper
        data-plasmic-name={"lottie"}
        data-plasmic-override={overrides.lottie}
        animationData={{
          v: "5.5.7",
          meta: { g: "LottieFiles AE 0.1.20", a: "", k: "", d: "", tc: "" },
          fr: 30,
          ip: 0,
          op: 121,
          w: 842,
          h: 596,
          nm: "sefaty sheild 2",
          ddd: 0,
          assets: [],
          layers: [
            {
              ddd: 0,
              ind: 1,
              ty: 4,
              nm: "Shape Layer 2",
              sr: 1,
              ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [418.938, 298, 0], ix: 2 },
                a: { a: 0, k: [-17, -21.5, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 }
              },

              ao: 0,
              shapes: [
                {
                  ty: "gr",
                  it: [
                    {
                      ind: 0,
                      ty: "sh",
                      ix: 1,
                      ks: {
                        a: 0,
                        k: {
                          i: [
                            [0, 0],
                            [0, 0],
                            [0, 0]
                          ],

                          o: [
                            [0, 0],
                            [0, 0],
                            [0, 0]
                          ],

                          v: [
                            [-75.875, -25.5],
                            [-34, 14],
                            [46, -57]
                          ],

                          c: false
                        },

                        ix: 2
                      },

                      nm: "Path 1",
                      mn: "ADBE Vector Shape - Group",
                      hd: false
                    },

                    {
                      ty: "tm",
                      s: { a: 0, k: 0, ix: 1 },
                      e: {
                        a: 1,
                        k: [
                          {
                            i: { x: [0.073], y: [0.955] },
                            o: { x: [0.453], y: [0] },
                            t: 61,
                            s: [0]
                          },

                          { t: 91, s: [100] }
                        ],

                        ix: 2
                      },

                      o: { a: 0, k: 0, ix: 3 },
                      m: 1,
                      ix: 2,
                      nm: "Trim Paths 1",
                      mn: "ADBE Vector Filter - Trim",
                      hd: false
                    },

                    {
                      ty: "st",
                      c: { a: 0, k: [0, 1, 1, 1], ix: 3 },
                      o: { a: 0, k: 100, ix: 4 },
                      w: { a: 0, k: 9, ix: 5 },
                      lc: 2,
                      lj: 1,
                      ml: 4,
                      bm: 0,
                      nm: "Stroke 1",
                      mn: "ADBE Vector Graphic - Stroke",
                      hd: false
                    },

                    {
                      ty: "tr",
                      p: { a: 0, k: [0, 0], ix: 2 },
                      a: { a: 0, k: [0, 0], ix: 1 },
                      s: { a: 0, k: [100, 100], ix: 3 },
                      r: { a: 0, k: 0, ix: 6 },
                      o: { a: 0, k: 100, ix: 7 },
                      sk: { a: 0, k: 0, ix: 4 },
                      sa: { a: 0, k: 0, ix: 5 },
                      nm: "Transform"
                    }
                  ],

                  nm: "Shape 1",
                  np: 4,
                  cix: 2,
                  bm: 0,
                  ix: 1,
                  mn: "ADBE Vector Group",
                  hd: false
                }
              ],

              ip: 1,
              op: 901,
              st: 1,
              bm: 0
            },

            {
              ddd: 0,
              ind: 2,
              ty: 4,
              nm: "Shape Layer 1",
              sr: 1,
              ks: {
                o: { a: 0, k: 25, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [418.938, 298, 0], ix: 2 },
                a: { a: 0, k: [-17, -21.5, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 }
              },

              ao: 0,
              shapes: [
                {
                  ty: "gr",
                  it: [
                    {
                      ind: 0,
                      ty: "sh",
                      ix: 1,
                      ks: {
                        a: 0,
                        k: {
                          i: [
                            [0, 0],
                            [0, 0],
                            [0, 0]
                          ],

                          o: [
                            [0, 0],
                            [0, 0],
                            [0, 0]
                          ],

                          v: [
                            [-75.875, -25.5],
                            [-34, 14],
                            [46, -57]
                          ],

                          c: false
                        },

                        ix: 2
                      },

                      nm: "Path 1",
                      mn: "ADBE Vector Shape - Group",
                      hd: false
                    },

                    {
                      ty: "tm",
                      s: { a: 0, k: 0, ix: 1 },
                      e: {
                        a: 1,
                        k: [
                          {
                            i: { x: [0.073], y: [0.955] },
                            o: { x: [0.453], y: [0] },
                            t: 60,
                            s: [0]
                          },

                          { t: 90, s: [100] }
                        ],

                        ix: 2
                      },

                      o: { a: 0, k: 0, ix: 3 },
                      m: 1,
                      ix: 2,
                      nm: "Trim Paths 1",
                      mn: "ADBE Vector Filter - Trim",
                      hd: false
                    },

                    {
                      ty: "st",
                      c: {
                        a: 0,
                        k: [0.752941191196, 0.752941191196, 0.752941191196, 1],
                        ix: 3
                      },

                      o: { a: 0, k: 100, ix: 4 },
                      w: { a: 0, k: 9, ix: 5 },
                      lc: 2,
                      lj: 1,
                      ml: 4,
                      bm: 0,
                      nm: "Stroke 1",
                      mn: "ADBE Vector Graphic - Stroke",
                      hd: false
                    },

                    {
                      ty: "tr",
                      p: { a: 0, k: [0, 0], ix: 2 },
                      a: { a: 0, k: [0, 0], ix: 1 },
                      s: { a: 0, k: [100, 100], ix: 3 },
                      r: { a: 0, k: 0, ix: 6 },
                      o: { a: 0, k: 100, ix: 7 },
                      sk: { a: 0, k: 0, ix: 4 },
                      sa: { a: 0, k: 0, ix: 5 },
                      nm: "Transform"
                    }
                  ],

                  nm: "Shape 1",
                  np: 4,
                  cix: 2,
                  bm: 0,
                  ix: 1,
                  mn: "ADBE Vector Group",
                  hd: false
                }
              ],

              ip: 0,
              op: 900,
              st: 0,
              bm: 0
            },

            {
              ddd: 0,
              ind: 3,
              ty: 4,
              nm: "safety shild Outlines 2",
              sr: 1,
              ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [420.945, 299.093, 0], ix: 2 },
                a: { a: 0, k: [107.229, 136.499, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 }
              },

              ao: 0,
              shapes: [
                {
                  ty: "gr",
                  it: [
                    {
                      ind: 0,
                      ty: "sh",
                      ix: 1,
                      ks: {
                        a: 0,
                        k: {
                          i: [
                            [6.142, 2.354],
                            [0, 0],
                            [3.665, -1.412],
                            [0, 0],
                            [0, -6.568],
                            [0, 0],
                            [-24.617, -17.826],
                            [0, 0],
                            [-17.209, 12.843],
                            [0, 0],
                            [0, 29.912],
                            [0, 0]
                          ],

                          o: [
                            [0, 0],
                            [-3.668, -1.406],
                            [0, 0],
                            [-6.129, 2.361],
                            [0, 0],
                            [0, 30.393],
                            [0, 0],
                            [17.392, 12.594],
                            [0, 0],
                            [23.972, -17.889],
                            [0, 0],
                            [0, -6.578]
                          ],

                          v: [
                            [77.032, -87.669],
                            [5.482, -115.092],
                            [-5.908, -115.083],
                            [-77.057, -87.678],
                            [-87.229, -72.858],
                            [-87.229, 13.52],
                            [-48.037, 90.287],
                            [-29.234, 103.904],
                            [28.925, 103.485],
                            [49.136, 88.401],
                            [87.229, 12.443],
                            [87.229, -72.84]
                          ],

                          c: true
                        },

                        ix: 2
                      },

                      nm: "Path 1",
                      mn: "ADBE Vector Shape - Group",
                      hd: false
                    },

                    {
                      ty: "st",
                      c: { a: 0, k: [0, 1, 1, 1], ix: 3 },
                      o: { a: 0, k: 100, ix: 4 },
                      w: { a: 0, k: 8, ix: 5 },
                      lc: 2,
                      lj: 1,
                      ml: 10,
                      bm: 0,
                      nm: "Stroke 1",
                      mn: "ADBE Vector Graphic - Stroke",
                      hd: false
                    },

                    {
                      ty: "tr",
                      p: { a: 0, k: [107.228, 136.499], ix: 2 },
                      a: { a: 0, k: [0, 0], ix: 1 },
                      s: { a: 0, k: [100, 100], ix: 3 },
                      r: { a: 0, k: 0, ix: 6 },
                      o: { a: 0, k: 100, ix: 7 },
                      sk: { a: 0, k: 0, ix: 4 },
                      sa: { a: 0, k: 0, ix: 5 },
                      nm: "Transform"
                    }
                  ],

                  nm: "Group 1",
                  np: 2,
                  cix: 2,
                  bm: 0,
                  ix: 1,
                  mn: "ADBE Vector Group",
                  hd: false
                },

                {
                  ty: "tm",
                  s: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.219], y: [1] },
                        o: { x: [0.61], y: [0] },
                        t: 1,
                        s: [50]
                      },

                      { t: 60, s: [100] }
                    ],

                    ix: 1
                  },

                  e: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.219], y: [1] },
                        o: { x: [0.61], y: [0] },
                        t: 1,
                        s: [50]
                      },

                      { t: 60, s: [0] }
                    ],

                    ix: 2
                  },

                  o: { a: 0, k: 45, ix: 3 },
                  m: 1,
                  ix: 2,
                  nm: "Trim Paths 1",
                  mn: "ADBE Vector Filter - Trim",
                  hd: false
                }
              ],

              ip: 1,
              op: 901,
              st: 1,
              bm: 0
            },

            {
              ddd: 0,
              ind: 4,
              ty: 4,
              nm: "safety shild Outlines",
              sr: 1,
              ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [420.945, 299.093, 0], ix: 2 },
                a: { a: 0, k: [107.229, 136.499, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 }
              },

              ao: 0,
              shapes: [
                {
                  ty: "gr",
                  it: [
                    {
                      ind: 0,
                      ty: "sh",
                      ix: 1,
                      ks: {
                        a: 0,
                        k: {
                          i: [
                            [6.142, 2.354],
                            [0, 0],
                            [3.665, -1.412],
                            [0, 0],
                            [0, -6.568],
                            [0, 0],
                            [-24.617, -17.826],
                            [0, 0],
                            [-17.209, 12.843],
                            [0, 0],
                            [0, 29.912],
                            [0, 0]
                          ],

                          o: [
                            [0, 0],
                            [-3.668, -1.406],
                            [0, 0],
                            [-6.129, 2.361],
                            [0, 0],
                            [0, 30.393],
                            [0, 0],
                            [17.392, 12.594],
                            [0, 0],
                            [23.972, -17.889],
                            [0, 0],
                            [0, -6.578]
                          ],

                          v: [
                            [77.032, -87.669],
                            [5.482, -115.092],
                            [-5.908, -115.083],
                            [-77.057, -87.678],
                            [-87.229, -72.858],
                            [-87.229, 13.52],
                            [-48.037, 90.287],
                            [-29.234, 103.904],
                            [28.925, 103.485],
                            [49.136, 88.401],
                            [87.229, 12.443],
                            [87.229, -72.84]
                          ],

                          c: true
                        },

                        ix: 2
                      },

                      nm: "Path 1",
                      mn: "ADBE Vector Shape - Group",
                      hd: false
                    },

                    {
                      ty: "st",
                      c: {
                        a: 0,
                        k: [0.752941191196, 0.752941191196, 0.752941191196, 1],
                        ix: 3
                      },

                      o: { a: 0, k: 100, ix: 4 },
                      w: { a: 0, k: 8, ix: 5 },
                      lc: 2,
                      lj: 1,
                      ml: 10,
                      bm: 0,
                      nm: "Stroke 1",
                      mn: "ADBE Vector Graphic - Stroke",
                      hd: false
                    },

                    {
                      ty: "tr",
                      p: { a: 0, k: [107.228, 136.499], ix: 2 },
                      a: { a: 0, k: [0, 0], ix: 1 },
                      s: { a: 0, k: [100, 100], ix: 3 },
                      r: { a: 0, k: 0, ix: 6 },
                      o: { a: 0, k: 100, ix: 7 },
                      sk: { a: 0, k: 0, ix: 4 },
                      sa: { a: 0, k: 0, ix: 5 },
                      nm: "Transform"
                    }
                  ],

                  nm: "Group 1",
                  np: 2,
                  cix: 2,
                  bm: 0,
                  ix: 1,
                  mn: "ADBE Vector Group",
                  hd: false
                },

                {
                  ty: "tm",
                  s: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.219], y: [1] },
                        o: { x: [0.61], y: [0] },
                        t: 0,
                        s: [50]
                      },

                      { t: 59, s: [100] }
                    ],

                    ix: 1
                  },

                  e: {
                    a: 1,
                    k: [
                      {
                        i: { x: [0.219], y: [1] },
                        o: { x: [0.61], y: [0] },
                        t: 0,
                        s: [50]
                      },

                      { t: 59, s: [0] }
                    ],

                    ix: 2
                  },

                  o: { a: 0, k: 45, ix: 3 },
                  m: 1,
                  ix: 2,
                  nm: "Trim Paths 1",
                  mn: "ADBE Vector Filter - Trim",
                  hd: false
                }
              ],

              ip: 0,
              op: 900,
              st: 0,
              bm: 0
            }
          ],

          markers: []
        }}
        className={classNames("__wab_instance", sty.lottie)}
        preview={true}
      />

      <div
        data-plasmic-name={"amountText"}
        data-plasmic-override={overrides.amountText}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.amountText
        )}
      >
        {"50000"}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "lottie", "amountText"],
  lottie: ["lottie"],
  amountText: ["amountText"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShieldLabel__ArgProps,
      internalVariantPropNames: PlasmicShieldLabel__VariantProps
    });

    return PlasmicShieldLabel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShieldLabel";
  } else {
    func.displayName = `PlasmicShieldLabel.${nodeName}`;
  }
  return func;
}

export const PlasmicShieldLabel = Object.assign(
  // Top-level PlasmicShieldLabel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    lottie: makeNodeComponent("lottie"),
    amountText: makeNodeComponent("amountText"),
    // Metadata about props expected for PlasmicShieldLabel
    internalVariantProps: PlasmicShieldLabel__VariantProps,
    internalArgProps: PlasmicShieldLabel__ArgProps
  }
);

export default PlasmicShieldLabel;
/* prettier-ignore-end */
