// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 32A6R5tEk8Q2nVvJmPnVbf
// Component: ubY-OV6QCB
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import MarketItemCard from "../../MarketItemCard"; // plasmic-import: hvcsRsK1439m/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_generic_landing_page.module.css"; // plasmic-import: 32A6R5tEk8Q2nVvJmPnVbf/projectcss
import sty from "./PlasmicMarketItemList.module.css"; // plasmic-import: ubY-OV6QCB/css

export const PlasmicMarketItemList__VariantProps = new Array();

export const PlasmicMarketItemList__ArgProps = new Array();

function PlasmicMarketItemList__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard__ojTax)}
      />

      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard___94Arm)}
      />

      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard__elAk)}
      />

      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard___9SrR)}
      />

      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard__l0FO4)}
      />

      <MarketItemCard
        className={classNames("__wab_instance", sty.marketItemCard__kWiDt)}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMarketItemList__ArgProps,
      internalVariantPropNames: PlasmicMarketItemList__VariantProps
    });

    return PlasmicMarketItemList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMarketItemList";
  } else {
    func.displayName = `PlasmicMarketItemList.${nodeName}`;
  }
  return func;
}

export const PlasmicMarketItemList = Object.assign(
  // Top-level PlasmicMarketItemList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMarketItemList
    internalVariantProps: PlasmicMarketItemList__VariantProps,
    internalArgProps: PlasmicMarketItemList__ArgProps
  }
);

export default PlasmicMarketItemList;
/* prettier-ignore-end */
