// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 32A6R5tEk8Q2nVvJmPnVbf
// Component: HXElpPSN5x
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: TCynlQ7-fD-aqs/component
import Button from "../../Button"; // plasmic-import: i6Jk8LEazvGVYD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../generic_landing_page/plasmic_generic_landing_page.module.css"; // plasmic-import: 32A6R5tEk8Q2nVvJmPnVbf/projectcss
import sty from "./PlasmicNftSellWidget.module.css"; // plasmic-import: HXElpPSN5x/css

export const PlasmicNftSellWidget__VariantProps = new Array("approve");

export const PlasmicNftSellWidget__ArgProps = new Array();

function PlasmicNftSellWidget__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {(hasVariant(variants, "approve", "approve") ? true : true) ? (
        <TextInput
          data-plasmic-name={"priceInput"}
          data-plasmic-override={overrides.priceInput}
          className={classNames("__wab_instance", sty.priceInput, {
            [sty.priceInputapprove]: hasVariant(variants, "approve", "approve")
          })}
          placeholder={"Price"}
        />
      ) : null}
      {(hasVariant(variants, "approve", "approve") ? true : true) ? (
        <div
          data-plasmic-name={"descText"}
          data-plasmic-override={overrides.descText}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.descText,
            {
              [sty.descTextapprove]: hasVariant(variants, "approve", "approve")
            }
          )}
        >
          {"Enter some text"}
        </div>
      ) : null}

      <Button
        data-plasmic-name={"sellButton"}
        data-plasmic-override={overrides.sellButton}
        className={classNames("__wab_instance", sty.sellButton, {
          [sty.sellButtonapprove]: hasVariant(variants, "approve", "approve")
        })}
        color={"primary"}
        round={true}
      >
        {hasVariant(variants, "approve", "approve") ? "Approve" : "Sell"}
      </Button>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "priceInput", "descText", "sellButton"],
  priceInput: ["priceInput"],
  descText: ["descText"],
  sellButton: ["sellButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNftSellWidget__ArgProps,
      internalVariantPropNames: PlasmicNftSellWidget__VariantProps
    });

    return PlasmicNftSellWidget__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNftSellWidget";
  } else {
    func.displayName = `PlasmicNftSellWidget.${nodeName}`;
  }
  return func;
}

export const PlasmicNftSellWidget = Object.assign(
  // Top-level PlasmicNftSellWidget renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    priceInput: makeNodeComponent("priceInput"),
    descText: makeNodeComponent("descText"),
    sellButton: makeNodeComponent("sellButton"),
    // Metadata about props expected for PlasmicNftSellWidget
    internalVariantProps: PlasmicNftSellWidget__VariantProps,
    internalArgProps: PlasmicNftSellWidget__ArgProps
  }
);

export default PlasmicNftSellWidget;
/* prettier-ignore-end */
