// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 32A6R5tEk8Q2nVvJmPnVbf
// Component: 6B_96A4ymw
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NftMintWidget from "../../NftMintWidget"; // plasmic-import: yv-K2ZiTgV/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../generic_landing_page/plasmic_generic_landing_page.module.css"; // plasmic-import: 32A6R5tEk8Q2nVvJmPnVbf/projectcss
import sty from "./PlasmicPopUp.module.css"; // plasmic-import: 6B_96A4ymw/css

export const PlasmicPopUp__VariantProps = new Array();

export const PlasmicPopUp__ArgProps = new Array("children");

function PlasmicPopUp__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return true ? (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <NftMintWidget
            className={classNames("__wab_instance", sty.nftMintWidget__vf2Cd)}
          />
        ),

        value: args.children
      })}
    </div>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPopUp__ArgProps,
      internalVariantPropNames: PlasmicPopUp__VariantProps
    });

    return PlasmicPopUp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPopUp";
  } else {
    func.displayName = `PlasmicPopUp.${nodeName}`;
  }
  return func;
}

export const PlasmicPopUp = Object.assign(
  // Top-level PlasmicPopUp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicPopUp
    internalVariantProps: PlasmicPopUp__VariantProps,
    internalArgProps: PlasmicPopUp__ArgProps
  }
);

export default PlasmicPopUp;
/* prettier-ignore-end */
