// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 32A6R5tEk8Q2nVvJmPnVbf
// Component: yv-K2ZiTgV
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: TCynlQ7-fD-aqs/component
import Button from "../../Button"; // plasmic-import: i6Jk8LEazvGVYD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../generic_landing_page/plasmic_generic_landing_page.module.css"; // plasmic-import: 32A6R5tEk8Q2nVvJmPnVbf/projectcss
import sty from "./PlasmicNftMintWidget.module.css"; // plasmic-import: yv-K2ZiTgV/css
import uploadPngImagespngP8LQzOkqL from "./images/uploadPngImagespng.png"; // plasmic-import: P8lQZOkqL/picture

export const PlasmicNftMintWidget__VariantProps = new Array();

export const PlasmicNftMintWidget__ArgProps = new Array();

function PlasmicNftMintWidget__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"imageInput"}
        data-plasmic-override={overrides.imageInput}
        alt={""}
        className={classNames(sty.imageInput)}
        displayHeight={"200px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"200px"}
        loading={"lazy"}
        src={{
          src: uploadPngImagespngP8LQzOkqL,
          fullWidth: 512,
          fullHeight: 512,
          aspectRatio: undefined
        }}
      />

      <TextInput
        data-plasmic-name={"titleInput"}
        data-plasmic-override={overrides.titleInput}
        className={classNames("__wab_instance", sty.titleInput)}
        placeholder={"Title..."}
      />

      <Button
        data-plasmic-name={"mintButton"}
        data-plasmic-override={overrides.mintButton}
        className={classNames("__wab_instance", sty.mintButton)}
        color={"primary"}
        round={true}
      >
        {"Mint"}
      </Button>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "imageInput", "titleInput", "mintButton"],
  imageInput: ["imageInput"],
  titleInput: ["titleInput"],
  mintButton: ["mintButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNftMintWidget__ArgProps,
      internalVariantPropNames: PlasmicNftMintWidget__VariantProps
    });

    return PlasmicNftMintWidget__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNftMintWidget";
  } else {
    func.displayName = `PlasmicNftMintWidget.${nodeName}`;
  }
  return func;
}

export const PlasmicNftMintWidget = Object.assign(
  // Top-level PlasmicNftMintWidget renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    imageInput: makeNodeComponent("imageInput"),
    titleInput: makeNodeComponent("titleInput"),
    mintButton: makeNodeComponent("mintButton"),
    // Metadata about props expected for PlasmicNftMintWidget
    internalVariantProps: PlasmicNftMintWidget__VariantProps,
    internalArgProps: PlasmicNftMintWidget__ArgProps
  }
);

export default PlasmicNftMintWidget;
/* prettier-ignore-end */
